Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -77,9 +77,20 @@ runs:
         # 2. 解压压缩包，并覆盖当前内核代码目录
         mkdir -p /tmp/rknpu_driver
         tar -xjvf /tmp/rknpu_driver.tar.bz2 -C /tmp/rknpu_driver
-        cp -r /tmp/rknpu_driver/*/* kernel/drivers/npu/
+        # 3. 查找 npu 目录
+        NPU_DIR=$(find kernel/drivers -type d -name 'npu' 2>/dev/null | head -n 1)
+
+        if [ -z "$NPU_DIR" ]; then
+          echo "NPU directory not found!"
+          exit 1
+        else
+          echo "Found NPU directory: $NPU_DIR"
+        fi
         
-        # 4. 修改内核头文件 kernel/include/linux/mm.h
+        # 4. 复制文件到目标目录
+        cp -r /tmp/rknpu_driver/*/* "$NPU_DIR/"
+        
+        # 5. 修改内核头文件 kernel/include/linux/mm.h
         HEADER_FILE="kernel/include/linux/mm.h"
         if [ -f "$HEADER_FILE" ]; then
             echo "static inline void vm_flags_set(struct vm_area_struct *vma, vm_flags_t flags) {" >> "$HEADER_FILE"
