Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -79,32 +79,33 @@ runs:
         tar -xjvf /tmp/rknpu_driver.tar.bz2 -C /tmp/rknpu_driver
         
         
-        # 3. 查找 kernel 目录
-        KERNEL_DIR=$(find / -type d -name 'kernel' 2>/dev/null | head -n 1)
+        # 3. 查找 rknpu_mm.c 所在的目录，搜索范围排除 /tmp/rknpu_driver
+        RKNPU_MM_FILE=$(find / -path /tmp/rknpu_driver -prune -o -name "rknpu_mm.c" -print 2>/dev/null)
 
-        if [ -z "$KERNEL_DIR" ]; then
-          echo "Kernel directory not found!"
+        if [ -z "$RKNPU_MM_FILE" ]; then
+          echo "rknpu_mm.c not found!"
           exit 1
         else
-          echo "Found Kernel directory: $KERNEL_DIR"
+          # 获取目录路径
+          RKNPU_DIR=$(dirname "$RKNPU_MM_FILE")
+          echo "Found rknpu_mm.c in: $RKNPU_DIR"
+          
+          # 获取除去 "drivers/rknpu" 后的 kernel 路径
+          KERNEL_PATH=$(echo "$RKNPU_DIR" | sed 's|/drivers/rknpu.*||')
+          echo "Kernel path: $KERNEL_PATH"
+          
+          # 设置 HEADER_FILE 路径
+          HEADER_FILE="$KERNEL_PATH/include/linux/mm.h"
+          echo "Header file will be modified: $HEADER_FILE"
         fi
         
-        # 4. 查找 rknpu 目录
-        RKNPU_DIR=$(find "$KERNEL_DIR/drivers" -type d -name 'rknpu' 2>/dev/null | head -n 1)
+        # 4. 复制文件到目标目录
+        echo "Copying files to $RKNPU_DIR..."
+        cp -r /tmp/rknpu_driver/drivers/rknpu/* "$RKNPU_DIR/" || { echo "Failed to copy files"; exit 1; }
 
-        if [ -z "$RKNPU_DIR" ]; then
-          echo "RKNPU directory not found!"
-          exit 1
-        else
-          echo "Found RKNPU directory: $RKNPU_DIR"
-        fi
-        
-        # 5. 复制文件到目标目录
-        cp -r /tmp/rknu_driver/drivers/rknpu/* "$RKNPU_DIR/"
-
-        # 6. 修改内核头文件 kernel/include/linux/mm.h
-        HEADER_FILE="$KERNEL_DIR/include/linux/mm.h"
+        # 5. 修改内核头文件
         if [ -f "$HEADER_FILE" ]; then
+            echo "Modifying header file: $HEADER_FILE"
             echo "static inline void vm_flags_set(struct vm_area_struct *vma, vm_flags_t flags) {" >> "$HEADER_FILE"
             echo "    vma->vm_flags |= flags;" >> "$HEADER_FILE"
             echo "}" >> "$HEADER_FILE"
