Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -77,10 +77,33 @@ runs:
         # 2. 解压压缩包，并覆盖当前内核代码目录
         mkdir -p /tmp/rknpu_driver
         tar -xjvf /tmp/rknpu_driver.tar.bz2 -C /tmp/rknpu_driver
-        cp -r /tmp/rknpu_driver/drivers/rknpu/* kernel/drivers/rknpu/
         
-        # 3. 修改内核头文件 kernel/include/linux/mm.h
-        HEADER_FILE="kernel/include/linux/mm.h"
+        
+        # 3. 查找 kernel 目录
+        KERNEL_DIR=$(find / -type d -name 'kernel' 2>/dev/null | head -n 1)
+
+        if [ -z "$KERNEL_DIR" ]; then
+          echo "Kernel directory not found!"
+          exit 1
+        else
+          echo "Found Kernel directory: $KERNEL_DIR"
+        fi
+        
+        # 4. 查找 rknpu 目录
+        RKNPU_DIR=$(find "$KERNEL_DIR/drivers" -type d -name 'rknpu' 2>/dev/null | head -n 1)
+
+        if [ -z "$RKNPU_DIR" ]; then
+          echo "RKNPU directory not found!"
+          exit 1
+        else
+          echo "Found RKNPU directory: $RKNPU_DIR"
+        fi
+        
+        # 5. 复制文件到目标目录
+        cp -r /tmp/rknu_driver/drivers/rknpu/* "$RKNPU_DIR/"
+
+        # 6. 修改内核头文件 kernel/include/linux/mm.h
+        HEADER_FILE="$KERNEL_DIR/include/linux/mm.h"
         if [ -f "$HEADER_FILE" ]; then
             echo "static inline void vm_flags_set(struct vm_area_struct *vma, vm_flags_t flags) {" >> "$HEADER_FILE"
             echo "    vma->vm_flags |= flags;" >> "$HEADER_FILE"
@@ -90,7 +113,7 @@ runs:
             echo "    vma->vm_flags &= ~flags;" >> "$HEADER_FILE"
             echo "}" >> "$HEADER_FILE"
         else
-            echo "$HEADER_FILE 不存在。"
+            echo "$HEADER_FILE does not exist."
         fi
 
         # 编译
